//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngLBDWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class home
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string Mobile { get; set; }
        public string Remarks { get; set; }
        public string Email { get; set; }
        public bool locDubaiBusines { get; set; }
        public bool locDubaiSilicon { get; set; }
        public bool Budget400K700K { get; set; }
        public bool Budget700K1000K { get; set; }
        public bool Budget1000K1250K { get; set; }
        public bool Budget1250K1500K { get; set; }
        public bool Studio { get; set; }
        public bool OneBed { get; set; }
        public bool TwoBed { get; set; }
        public bool Retail { get; set; }
        public bool Immed { get; set; }
        public bool Months3to6 { get; set; }
        public bool Months6to12 { get; set; }
        public bool Months12to18 { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<byte> SourceID { get; set; }
    }
}
