//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngLBDWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int RegisterID { get; set; }
        public string Email { get; set; }
        public string Company { get; set; }
        public string JobTitle { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Country { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> entry { get; set; }
        public string Mobile { get; set; }
    }
}
